- platform: group
  name: Zen Lamp
  entities:
  - light.zen_bottom
  - light.zen_top

- platform: group
  name: Bedroom Area
  entities:
  - light.zen_bottom
  - light.zen_top
  - light.bedside_left
  - light.bedside_right

- platform: group
  name: Main Area
  entities:
  - light.living_room_main_lights
  - light.entrance
  - light.dining_room_main_lights
  - light.hallway_main_lights

- platform: group
  name: Kitchen Area
  entities:
  - light.nook
  - light.kitchen_main_lights
  - light.sink
  - light.utility_room

  #######   SWITCHES BEING CONVERTED TO LIGHTS
  
- platform: switch
  name: Garage Light
  entity_id: switch.garage_light

- platform: switch
  name: Office Floor Lamp
  entity_id: switch.office_floor_lamp
    
- platform: switch
  name: Patio Lights
  entity_id: switch.patio_lights

- platform: switch
  name: Chicken Coop Light
  entity_id: switch.chicken_coop_light

- platform: switch
  name: Bedroom Fan Light
  entity_id: switch.bedroom_fan_light

- platform: switch
  name: Office Fan Light
  entity_id: switch.office_fan_light
