#- platform: group
  #name: Bedroom
  #entities:
  #- group.bedsidetable
  #- group.zenlamp

- platform: group
  name: Bedroom Area
  entities:
  - light.zen__bottom
  - light.zen__top
  - light.bedside__left
  - light.bedside__right

- platform: group
  name: Main Area
  entities:
  - light.living_room_main_lights
  - light.entrance
  - light.dining_room_main_lights
  - light.hallway_main_lights

- platform: group
  name: Kitchen Area
  entities:
  - light.nook
  - light.kitchen_main_lights
  - light.sink
  
#- platform: group
#  name: Utility Room
#  entities:  
#  - switch.pantry
#  - switch.utility_room

- platform: group
  name: Outdoors
  entities:
  #- switch.patio_lights
  - light.porch
  
- platform: group
  name: Sunset Off
  entities:
  - light.office
  #- switch.pantry
  #- switch.utility_room

- platform: group
  name: Sunset Dim
  entities:
  - light.Kitchen_main_lights
  - light.living_room_main_lights
  - light.dining_room_main_lights
  - light.hallway_main_lights
  - light.entrance
  - light.office_table
  
- platform: group
  name: Late Night Off
  entities:
  - light.office
  #- switch.pantry
  #- switch.utility_room

- platform: group
  name: Late Night Dim
  entities:
  - light.Kitchen_main_lights
  - light.living_room_main_lights
  - light.dining_room_main_lights
  - light.hallway_main_lights
  - light.office_table
  - light.entrance
  
  
  